# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VictorTask1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VictorTask1
  pod 'Mantle'
  #pod 'Realm'
  #, '~>10'
  pod 'RealmSwift'
  #pod 'ResearchKit'

end
